.TH "DOLFIN-GET-DEMOS" 1

.SH NAME
dolfin-get-demos - install DOLFIN demos in user's home direcotry

.SH SYNOPSIS
.B dolfin-get-demos

.SH BUGS
.TP
For comments, questions, bug reports etc. see http://fenicsproject.org/support.

.SH AUTHOR
dolfin-get-demos was written by Anders Logg <logg@chalmers.se>.
